name: install
description: Install specific version of Deno

inputs:
  deno-version:
    description: Deno version
    default: v1.x
    required: false

runs:
  using: composite
  steps:
    - name: Install Deno version ${{ inputs.deno-version }}
      uses: denoland/setup-deno@v1
      with:
        deno-version: ${{ inputs.deno-version }}
    - name: Install tools
      shell: bash
      run: deno task install
