name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install project prerequisite
        uses: ./.github/actions/install-action
      - name: Check format
        run: deno task format
      - name: Check lint
        run: deno task lint

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install project prerequisite
        uses: ./.github/actions/install-action
      - name: Run tests
        run: deno task cover
      - name: Upload lcov coverage report file to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ${{ github.workspace }}/dist/coverage/coverage.lcov
